<a href="https://colab.research.google.com/github/Sri-addanki-5/python/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Write a program that takes a word W as input and prints "Hello" followed by the given word W.
name=input()
print("Hello "+name)

srikanth
Hello srikanth


In [ ]:
#String Repetition
# Write a program to print the given input word three times in a single line separated by spaces
word = input()
message = (word + ' ') * 3
print(message)

srikanth
srikanth srikanth srikanth 


In [ ]:
a = input()
a = int(a)
b = input()
b = int(b)
result = a+b
print(result)


2
3
5


In [ ]:
word = input()
n = input()
n = int(n)
print(word[n])

srikanth
2
i


In [ ]:
length = input()
breadth = input()
length = int(length)
breadth = int(breadth)
area_of_rectangle = length*breadth
print(area_of_rectangle)

20
30
600


In [ ]:
#perimeter of rectangle
length = input()
breadth = input()
length = int(input())
breadth = int(input())
sum_of_two_sides = length+breadth
perimeter_of_rectangle = 2*sum_of_two_sides
print(perimeter_of_rectangle)

In [ ]:
first_str = input()
snd_str = input()
first_str_part = first_str[:3]
second_str_part = snd_str[:3]
are_both_same = first_str_part == second_str_part
print(are_both_same)

In [ ]:
a =input()
b = input()
a = int(a)
b = int(b)
is_both_positive = a > 0 and b > 0
is_one_greater = a>5 or b > 5
result = is_both_positive and is_one_greater
print(result)

In [ ]:
n = int(input())
counter = 1
while counter <=n:
    print(counter)
    counter = counter +1 

In [ ]:
m = int(input())
n = int(input())
for number in range(m,n+1):
  print(number)

In [ ]:
m = int(input())
n = int(input())
for number in range(m):
  print("* " *n)

In [ ]:
 m = int(input())
 for number in range(1,m+1):
   print("* "*number)

In [ ]:
n = int(input())
total = 0
for i in range(n):
  m = int(input())
  total = total+m
print(total) 

In [ ]:
a = input()
length = len(a)
b = a[0]
for i in range(1,length):
  b = b + "-" +a[i]
print(b)  


In [ ]:
date = input()
date = date.replace("-","/")
print(date)

In [ ]:
password = input()
contains_digit = False
for character in password:
  is_digit =character.isdigit()
  if is_digit:
    contains_digit = True
if contains_digit:  
  print("valid password")
else:
  print("not valid")  

In [ ]:
word = input()
modified = ""
for char in word:
  uppercase = char.upper()
  if uppercase == char:
    modified += char.lower()
  else:
    modified +=char.upper()
print(modified)      

In [ ]:
# Factorial
n = int(input())
factorial = 1
for i in range(1,n+1):
  factorial = factorial * i
print(factorial)  

In [ ]:
m = int(input())
n = int(input())
total = 0
for i in range(m,n+1):
  total += i
print(total)  

In [ ]:
n = int(input())
total = 0
for i in range(1,n+1):
  if i%2==1:
    total += i
print(total)    

In [ ]:
#sum of numbers divisible by T
t = int(input())
m = int(input())
n = int(input())
total = 0
for number in range(m,n+1):
  if number%t ==0:
    total +=number
print(total)    

In [ ]:
#sum of squares
n = int(input())
total = 0
for i in range(1,n+1):
  total += ()
print(total)  

In [ ]:
n=int(input())
total=0
for i in range(1,n+1):
    total=total+(i*i)
print(total)

In [ ]:
#sum of average 10 numbers
total = 0
for i in range(10):
  number = int(input())
  total +=number
average = total/10
print(total)
print(average)  

In [ ]:
number = input()
total =0
for digit in number:
  total = total+int(digit)
print(total)

In [ ]:
a = int(input())
for i in range(1,11):
  print(str(a)+"*"+str(i)+"="+str(i*a))

In [ ]:
#Reverse string
a = input()
rever = ""
for i in a:
  rever = i+rever
print(rever)  


In [ ]:
#palindrome
n = input()
n = n.lower()
reverse_n = ""
for char in n:
  reverse_n = char+reverse_n
if n == reverse_n:
  print("palindrome")
else:
  print("not a palindrome")    

In [ ]:
#Greatest among N numbers
n = int(input())
first_input = int(input())
greatest_number = first_input
for i in range(n-1):
  num = int(input())
  if num > greatest_number:
    greatest_number = num
print(greatest_number)    

In [ ]:
#smallest number
n = int(input())
first_number = int(input())
smallest_number = first_number
for i in range(n-1):
  num = int(input())
  if num < smallest_number:
    smallest_number = num
print(smallest_number)    

In [ ]:
#factors of numbers
n = int(input())
for i in range(1,n+1):
  if n%i ==0:
    print(i)

In [ ]:
#sum odf all factors
n = int(input())
total = 0
for i in range(1,n+1):
  if n%i ==0:
    total = total + i
print(total)    

In [ ]:
# perfect number
n = int(input())
total = 0
for i in range(1,n):
  if n%i == 0:
    total+=i
if total == n:
  print("perfect number")
else:
  print("not perfect number")      

In [ ]:
# armstrong number
n = input()
length = len(n)
total = 0
for digit in n:
  total = total+(int(digit)**length)
if total ==int(n):
  print("Armstrong number")
else:
  print("Not an armstrong number")    

In [ ]:
#OOPS

In [ ]:
#CAR
class Car:
    def __init__(self,color,max_speed,acceleration,tyre_friction):
        self.color = color
        self.max_speed=max_speed
        self.acceleration=acceleration
        self.tyre_friction=tyre_friction
        
    # def default_test():
car=Car(color="Red",max_speed=250,acceleration=10,tyre_friction=3)
print(car.color)
print(car.max_speed)
print(car.acceleration)
print(car.tyre_friction)

In [ ]:
#Car-2


In [ ]:
class Car:
  def __init__(self,color,max_speed,acceleration,tyre_friction):
    self.color = color
    self.max_speed = max_speed
    self.acceleration = acceleration
    self.tyre_friction = tyre_friction
    self.is_engine_started = False
  def start_engine(self):
    self.is_engine_started = True
  def stop_engine(self):
    self.is_engine_started = False 
car = Car(color = 'Red',max_speed = 250,acceleration = 10,tyre_friction = 3)
print(car.color)
print(car.max_speed)
print(car.acceleration)
print(car.tyre_friction)
car.start_engine()
print(car.is_engine_started)
car.stop_engine()
print(car.is_engine_started)      

In [ ]:
# Car-3

In [ ]:
class Car:
  def __init__(self,color,max_speed,acceleration,tyre_friction):
    self.color = color
    self.max_speed = max_speed
    self.acceleration = acceleration
    self.tyre_friction = tyre_friction
    self.is_engine_started = False
    self.current_speed = 0
  def start_engine(self):
    self.is_engine_started = True
  def stop_engine(self):
    self.is_engine_started = False
  def accelerate(self):
    if not self.is_engine_started:
      print("Car has not started yet")
    else:
      self.current_speed += self.acceleration
      if self.current_speed > self.max_speed:
        self.current_speed =self.max_speed 
car = Car(color = "Red",max_speed = 250, acceleration = 10, tyre_friction = 3)
car.accelerate()
print(car.current_speed)
car.start_engine()
print(car.current_speed)
car.accelerate()
print(car.current_speed)
car.accelerate()
print(car.current_speed)
car.accelerate()
car.accelerate()
car.accelerate()
print(car.current_speed)



In [ ]:
# A car and Truck incomplete classes

In [ ]:
class Car:
  def __init__(self,color,max_speed,acceleration,tyre_friction):
    self.color = color
    self.max_speed = max_speed
    self.acceleration = acceleration
    self.tyre_friction = tyre_friction
    self.is_engine_started = False
    self.current_speed = 0
  def start_engine(self):
    self.is_engine_started = True
  def stop_engine(self):
    self.is_engine_started = False
  def acceleration(self):
    if not self.is_engine_started:
      print("car not started yet")
    else:
      self.current_speed += self.acceleration
      if slef.current_speed > self.max_speed:
        self.current_speed = self.max_speed
  def apply_brakes(self):
    self.current_speed -= self.tyre_friction
    if self.current_speed < 0:
      self.current_speed = 0
  def sound_horn(self):
    if self.is_engine_started:
      print("Beep Beep")
    else:
      print("Car has not started yet")
class Truck(Car):
  def __init__(self,color,max_speed,acceleration,tyre_friction,max_cargo_weight):
    super().__init__(color,max_speed,acceleration,tyre_friction)
    self.max_cargo_weight = max_cargo_weight
    self.load = 0
  def load_cargo(self,cargo_weight):
    if self.is_engine_started:
      pribt("cannot load cargo during motion")
    elif cargo_weight + self.load > self.max_cargo_weight:
      print("cannot load cargo morethan max limit:{}".format(self.max_cargo_weight))
    else:
      self.load += cargo_weight
  def unload_cargo(self,cargo_weight):
    if self.is_engine_started:
      print("cannot unload cargo during motion")
    else:
      self.load -= cargo_weight
      if self.load < 0:
        self.load = 0
  def sound_horn (self):
    if self.is_engine_started:
      print("honk honk")
    else:
      print("car has not started yet")
truck = Truck(color = "red",max_speed = 250,acceleration = 10,tyre_friction = 3,max_cargo_weight=100)
print(truck.is_engine_started)
truck.load_cargo(cargo_weight=50)
print(truck.load)
truck.unload_cargo(cargo_weight=25)
print(truck.load)
truck.unload_cargo(cargo_weight = 70)
print(truck.load)
truck.unload_cargo(cargo_weight=120)
print(truck.load)  
truck.sound_horn()
truck.stop_engine()
truck.sound_horn()          



In [ ]:
#car 4
class Car:
  def __init__(self,color,max_speed,acceleration,tyre_friction):
    self.color = color
    self.max_speed = max_speed
    self.acceleration = acceleration
    self.tyre_friction = tyre_friction
    self.is_engine_started = False
    self.current_speed = 0
  def start_engine(self):
    self.is_engine_started = True
  def stop_engine(self):
    self.is_engine_started = True
  def accelerate(self):
    if not self.is_engine_started:
      print("car has not started yet")
    else:
      self.current_speed +=self.acceleration
      if self.current_speed > self.max_speed:
          self.current_speed = self.max_speed  
car = Car("Red",max_speed = 50,acceleration = 10,tyre_friction = 3)
car.start_engine()
print(car.current_speed)
car.stop_engine()
car.accelerate()
print(car.current_speed)
                

In [ ]:
# #parsing datetime
# from datetime import datetime

# date = input()
# date_string = "%d %b %Y"
# datetime_object = datetime.strptime(date,date_string)
# print(datetime_object)

In [ ]:
#lists

In [ ]:
player = ["Rose",183,148,123.64,False]
print(player)

In [ ]:
#list concatination
num = [20,30,20,40,100]
n = int(input())
sri_1 = num+[n]
sri_2 = [n]+num
print(sri_1)
print(sri_2)

In [ ]:
#convert string to list


In [ ]:
programing_language = ["python","java","rubey","machin_learning","c","c++"]
n = int(input())
for i in range(n):
  index = int(input())
  print(programing_language[index])  



In [ ]:
#list repetation
m = int(input())
n = int(input())
list_a = [m]*n
print(list_a)

In [ ]:
# Greater than N
num_list = [4,6,45,34,54,65,76,46,34,31,78,96]
n = int(input())
num_rum = []
for i in num_list:
  if i > n:
    num_rum += [i]
print(num_rum)   

In [ ]:
#create print_list
n = int(input())
list_1 = []
for i in range(n):
  value = input()
  list_1 += [value]
print(list_1)  

In [ ]:
n = int(input())
list_1 = []
list_2 = []
for i in range(n):
  value = input()
  list_1 += (value)
for n in list_1:
  if n ==list_1:
    list_2 += n
print(list_2)    


print(list_1)



In [ ]:
# reverse order
n = int(input())
list_a = []
for i in range(n):
  value = input()
  list_a +=[value]
for i in range(n):
  print(list_a[n-i-1])  

In [ ]:
# list concatination
n=int(input())
list_a = []
for i in range(n):
    value = input()
    list_a += [value]
    new_list=list_a[:3] + list_a[n-3:]
print(new_list)

In [ ]:
# functions 

In [ ]:
#splite the sentence
n = input()
word_list = n.split()
sri = ""
for word in word_list:
  pass
  if word == "srikanth":
    sri += word
print(sri)    

print(word)

In [ ]:
#sum of list elements
n=input()
num_list=n.split()
total=0
for n in num_list:
    total=total+int(n)
print(total)  

In [ ]:
strin = input()
spli = strin.split()
sri = []
for n in spli:
  sri += [n[::-1]]
reverse_order =" ".join(sri)
print(reverse_order)  

In [ ]:
def wishes(name):
  wish = "welcome "+ name
  return wish
a = input()
wishes(a)

In [ ]:
#multiplay with three
def multiply_with_three(num):
   number = num*3
   print(number)
n = int(input())
multiply_with_three(n)   

In [ ]:
# divisible by 7
def divisible_by_7(num):
  number = num/7
  print(number)
n = int(input())
divisible_by_7(n)
  

In [ ]:
# perimeter of square
def perimeter(four):
  result = four*4
  print(result)
a = int(input())
perimeter(a)  

In [ ]:
# add two numbers
def sum_of_two(num1,num2):
  value = num1+num2
  print(value)
a = int(input())
b = int(input())
sum_of_two(a,b)  

In [ ]:
# second character in the word
def word_second(num):
  character = num[1]
  return character
a = input()
word_second(a)  

In [ ]:
# indexing
def indexing(arg1,arg2):
  character = arg1[arg2]
  return character
a = input()
index = int(input())
indexing(a,index)  

In [ ]:
# printing message
def name(arg1,arg2):
  character = arg1 + " is " +str(arg2)+" years old"
  return character
a = input()
b = int(input())
name(a,b)  

In [ ]:
#number of upper and lowercase letters
def upper_lower(arg):
  count_uppercase = 0
  count_lowercase = 0
  for char in arg:
    if char.upper() == char:
      count_uppercase += 1
    else:
      count_lowercase += 1
  print(count_uppercase)
  print(count_lowercase)
a = input()
upper_lower(a)        

In [ ]:
# list of squares
def get_list(string_a):
    list_a = string_a.split(',')
    len_list_a = len(list_a)
    for i in range(len_list_a):
        list_a[i] = int(list_a[i])**2
    return list_a


string_a = input()
numbers_list = get_list(string_a)
print(numbers_list)    

In [ ]:
# So the output should be
# [1, 2, 5]
#input=5
#append 5
#insert 0,2
#append 1
#sort
#print
n = int(input())

nums_list = []
for i in range(n):
    command = input().split()
    if command[0] == 'insert':
        index = int(command[1])
        value = int(command[2])
        nums_list.insert(index, value)
    elif command[0] == 'append':
        value = int(command[1])
        nums_list.append(value)
    elif command[0] == 'pop':
        nums_list.pop()
    elif command[0] == "remove":
        value = int(command[1])
        nums_list.remove(value)
    elif command[0] == "sort":
        nums_list.sort()
    elif command[0] == "print":
        print(nums_list)

In [ ]:
# Team points
def calculateLeagues(wins,draws,losses):
  wins_points = wins*4
  draws_points = draws*2
  losses_points = losses*-1
  total_points = wins_points+losses_points+draws_points
  return total_points
statistics = input().split(",")
wins = int(input())
draws = int(input())
losses = int(input())
total_points = calculateLeagues(wins,draws,losses)
print(total_points)  

In [ ]:
# speed meter
def get_speed_status(speed):
  if (speed >= 60 and speed<80):
    msg = "Normal"
  elif (speed>=60) and (speed<80):
    msg = "Warning"
  else:
    msg = "Over speed"
  return msg
speed = int(input())
a = get_speed_status(speed)
print(a)  


In [ ]:
# Wather Reporter
def get_weather_report(temp):
  if temp < 22:
    report = "Cold"
  elif (temp >= 22) and (temp<35):
    report = "Warm"
  else:
    report = "Hot"
  return report
temp = int(input())
a = get_weather_report(temp)
print(a)    


In [ ]:
# Discount
def discount_for_shoping(bill):
  if (bill > 250) and (bill <= 450):
    discount = "5%"
  elif (bill >= 450) and (bill <= 850):
    discount = "10%"
  else:
    discount = "15%"
  return discount
bill = int(input())
so = discount_for_shoping(bill)
print(so)        


In [ ]:
# calculte bill
def calculate_bill(amount):
  if amount <500:
    bill = amount-(amount * 0.05)
  elif (amount >= 500) and (amount < 2500):
    bill = amount-(amount*0.01)
  else:
    bill = amount-(amount*0.2)
  bill = round(bill,3)
  return bill
amount = int(input())
a = calculate_bill(amount)
print(a)  



In [ ]:
#Fiz buzz
def fizz_buzz(number):
    is_divisible_by_3= (number%3)==0
    is_divisible_by_5=(number%5)==0
    is_divisible_by_both = is_divisible_by_3 and is_divisible_by_5
    
    if is_divisible_by_both:
        msg = "FizzBuzz"
    elif is_divisible_by_3:
        msg= "Fizz"
    elif is_divisible_by_5:
        msg="Buzz"
    else:
        msg=number
    return msg
    
number = int(input())
result = fizz_buzz(number)
print(result)

In [ ]:
n = int(input())
count = 1
while (count <= n):
  print(count)
  count += 1
  


In [ ]:
# integers
n = int(input())
count = 2
while count<=6:
  print(count)
  count+=1

In [ ]:
# triangle
n = int(input())
count = 4
while count <= n:
  print("*"*count)
  if count <= 0:
    break
  count -=1


In [ ]:
# solid square
n = int(input())
count = 0
while count <= n:
  print("* "*n)
  count +=1

In [ ]:
# solid rectangle
row = int(input())
col = int(input())
count = 0
while count <= row:
  print("* "*col
        )
  count +=1


In [ ]:
row = int(input())
col = int(input())
count = 0
while count <= row:
  print("* "*col)
  if count == 4:
    break
  count +=1  

In [ ]:
# sum of natural numbers
num = int(input())
sum = 0
count = 0
while count <= num:
  sum += count
  count +=1
print(sum)  


In [ ]:
n = int(input())
count = 1
while count <= n:
  print("* "*count)
  count+=1

In [ ]:
#Read N Inputs
num = int(input())
count = 0
while count <= num:
  n = int(input())
  print(n)
  count +=1



In [ ]:
# sum of the given numbers
n = int(input())
total = 0
for number in range(n):
  m = int(input())
  total +=m
print(total)  

In [ ]:
n = input()
len_of_a = len(n)
b = n[0]
for i in range(1,len_of_a):
  b = b + '-' +n[i]
print(b)  


In [ ]:
date = input()
date = date.replace("-","/")
print(date)

In [ ]:
word = input()
lower_case = word.lower()
upper_case = word.upper()
print(lower_case)
print(upper_case)

In [ ]:
# valid password
password=input()
contains_digit=False
for character in password:
    is_digit=character.isdigit()
    
    if is_digit:
        contains_digit=True
if contains_digit:
    print("Valid Password")
else:
    print("Invalid Password")     
    


In [ ]:
# This program prints Hello, world!
print("Hello, world!")

In [ ]:
# This program adds two numbers
num = 1.5
num2 = 3.5
sum = num+num2
print(sum)

In [ ]:
a = input("enter first number:")
b = input("enter second number:")
sum = float(a)+float(b)
print(sum)

In [ ]:
# Python Program to calculate the square root
num = 8
num_sqrt = num**0.5
print(num,num_sqrt)

In [ ]:
# Python Program to find the area of triangle
a = int(input())
b= int(input())
c = int(input())
s = ((a+b+c)/2)
n1 = (s-a)*(s-b)*(s-c)
n2 = (s*n1)
area = n2**0.5
print(area)

In [ ]:
# Solve the quadratic equation ax**2 + bx + c = 0
a = int(input())
b = int(input())
c = int(input())
d = ((b**2) - 4*a*c)
sol1 = ((-b+d**0.5)/2)*a
sol2 = ((-b-d**0.5)/2)*a
print(sol1,sol2)


In [ ]:
# Python program to swap two variables
x = 5
y = 10
temp = x
x = y
y = temp
print(x,y)

In [ ]:
# Program to generate a random number between 0 and 9
import random
print(random.randint(0,9))

In [ ]:
#Python Program to Convert Kilometers to Miles
kilometers = float(input("enter the kilometers:"))
conversion = 0.621371
miles = kilometers*conversion
print(miles)

In [ ]:
#9_Python Program to Convert Celsius To Fahrenheit


In [ ]:
celsius = float(input())
fahrenhit = (celsius*1.8)+32
print(fahrenhit)


In [ ]:
#Python Program to Check if a Number is Positive, Negative or 0
num = int(input("enter number here:"))
if num >= 0:
  print("positive")
elif num == 0:
  print("Zero")
else:
  print("Negative")    

In [ ]:
#Python Program to Check if a Number is Odd or Even
num = int(input("Enter the number here:"))
if (num%2==0):
  print("Even number")
else:
  print("Odd number")  

In [ ]:
#Python Program to Check Leap Year
year = 2012
if (year%4) == 0:
  if (year%100) == 0:
    if (year%400) == 0:
      print("leap year")
    else:
      print("not a leap year")
  else:   
    print("leap year")
else:
  print("not a leap year")      

In [ ]:
# Python program to find the largest number among the three input numbers
num1=10
num2=20
num3=18
if (num1 >= num2) and (num1>= num3):
  largest = num1
elif (num2 >= num1) and (num2 >= num3):
  largest = num2
else:
  largest = num3
print(largest)  


In [ ]:
# Program to check if a number is prime or not
n = int(input())
if n > 1:
  for i in range(2,n):
    if (n%i ==0):
      print("it is not a prime number")
      break
  else:
    print("prime number")
else:
  print("it is not a prime number")
# Program to check if a number is prime or not    
def prime(num):
  if num > 1:
    for i in range(2,num):
      if (num%i == 0):
        return "it is not a prime number"
        break
    else:
      return "prime number"
  else:
    return "it is not a prime number"
a = int(input())
print(prime((a)))    



In [ ]:
# Python program to display all the prime numbers within an interval
def prime(num1,num2):
  for num in range(num1,num2+1):
    if num > 1:
      for i in range(2,num):
        if (num%i == 0):
          return num
          break
      else:
        return num
    
num1 = int(input())
num2 = int(input())
print(prime(num1,num2))                

In [ ]:
# Python program to find the factorial of a number provided by the user.
num = 7
factorial = 1
if num < 0:
  print("factorial doesn't exist negative numbers")
elif num == 0:
  print("The factorial of 0 is 1")
else:
  for i in range(1,num+1):
    factorial = factorial*i
  print(factorial)      

In [ ]:
# Multiplication table (from 1 to 10) in Python
num = 10
for i in range(1,num+1):
  print(num,"*",str(i)+ " =",str(num*i))

In [ ]:
# Program to display the Fibonacci sequence up to n-th term
num  = 10
sri = 0
n1,n2 = 0,1
while sri <= num:
  print(n1)
  nth = n1+n2
  n1 = n2
  n2 = nth
  sri+=1



In [ ]:
# Python program to check if the number is an Armstrong number or not


In [ ]:
#Given two integer numbers return their product. If the product is greater than 1000, then return their sum
num1 = int(input())
num2 = int(input())
pro = num1*num2
if pro < 1000:
  print("The result is",pro)
else:
  print(num1+num2)  

In [ ]:
#Given a range of the first 10 numbers, Iterate from the start number to the end number, and In each iteration print the sum of the current number and previous number


In [ ]:
#4: Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string
def remove_Char(str,n):
  return str[n:]
print(remove_Char("pynative",4))  

In [ ]:
#5: Given a list of numbers, return True if first and last number of a list is same
def isFirst_lastFirst(numList):
  firstElement = numList[0]
  lastElement = numList[-1]
  if firstElement == lastElement:
    return True
  else:
    return False
print(isFirst_lastFirst([10,20,30,40,10]))      


In [ ]:
#6: Given a list of numbers, Iterate it and print only those numbers which are divisible of 5
def list_divisible(num):
  for sri in num:
    if sri%5==0:
      print(sri)
list_divisible([10,20,33,46,55]) 

In [ ]:
#7: Return the count of sub-string “Emma” appears in the given string
def sub_string(strn):
  return "Emma appeared  "+ str(strn.count("Emma"))+" Times"
sub_string("Emma is good developer. Emma is a writer")  

In [ ]:
def count_emma(stmt):
  count = 0
  for i in range(len(stmt)-1):
    count += stmt[i:i+4] == "Emma"
  return count
print(count_emma("Emma is good developer. Emma is a writer"))    

In [ ]:
# 8: Print the following pattern
for num in range(6):
    for i in range(num):
        print (num, end=" ") #print number
    # new line after each row to display pattern correctly
    print("\n")
  

In [ ]:
num = int(input())
previous = 0 
for i in range(0,num):
  sum = previous + i
  print("Current Number",str(i),"previousNum",str(previous),"Sum:",str(sum))

In [ ]:
#3: Given a string, display only those characters which are present at an even index number.
sri = "pynative"
dm = sri[0::2]
for i in dm:
  print(i)

In [ ]:
# 4: Given a string and an integer number n, remove characters from a string starting from zero up to n and return a new string


In [ ]:
#Find product of all numbers present in a list
lst = [10,20,30,40,50]
product = 1
index = 0
while index < len(lst):
  product *= lst[index]
  index += 1
print("product is {}".format(product))  


product is 12000000


In [ ]:
lst = int(input())
vb = str(lst)
product = 1
index = 0
while index < len(vb):
  index +=1
  print(index)




10
1
2


In [ ]:
num = int(input("Enter the number:"))
isDivisible = False
i = 2
while i < num:
  if num % i == 0:
    isDivisible = True
    print("{} is divisible in {}".format(num,i))
  i += 1
if isDivisible:
  print("{} is not a prime number".format(num))
else:
  print("{} is a prime number".format(num))    



Enter the number:8
8 is divisible in 2
8 is divisible in 4
8 is not a prime number


In [ ]:
lst = ["srikanth",3.44,45,]
lst.append("kanth")
print(lst)

['srikanth', 3.44, 45, 'kanth']


In [ ]:
print(len(lst))

4


In [ ]:
lst.insert(2,"madhuri")
print(lst)

['srikanth', 3.44, 'madhuri', 45, 'kanth']


In [ ]:
del lst[1]
print(lst)

['srikanth', 'madhuri', 45, 'kanth']


In [ ]:
if "srikanth" in lst:
  print("AI")
else:
  print("Blockchain")  

AI


In [ ]:
lst.reverse()
print(lst)

['kanth', 45, 'madhuri', 'srikanth']


In [ ]:
numbers = [1,2,3,4,5,4,3,2,5,3,5]
sorted_list = sorted(numbers)
print(sorted_list)

[1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5]


In [ ]:
lst = [1,20,'b',5,'a']
print(lst.sorted())

AttributeError: ignored

In [ ]:
lst = [1,3,4,5,6]
abc= lst
abc.append(6)
print("original list",lst)
print("after changed list:",abc)

original list [1, 3, 4, 5, 6, 6]
after changed list: [1, 3, 4, 5, 6, 6]


String split to create a list


In [ ]:
s =  "pdb.set_trace is Enter the debugger at the calling stack frame. This is useful to hard-code a breakpoint at a given point in a program, even if the code is not otherwise being debugged (e.g. when an assertion fails). If given, header is printed to the console just before debugging begins."
split_list = s.split()
s = len(split_list)
print(s)


  
# for i in range():
# print(split_list)

50


In [ ]:
#without list comprehensions
squares = []
for i in range(10):
  squares.append(i)
print(squares)  


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#using list comprehensions
sqaures = [i**2 for i in range(10)]
print(sqaures)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
lst = [i%2 == 0 for i in range(10)]
print(lst)

[True, False, True, False, True, False, True, False, True, False]


In [ ]:
lst = [i^2 for i in range(10)]
print(lst)

[2, 3, 0, 1, 6, 7, 4, 5, 10, 11]


In [ ]:
[i for i in lst if i>=2]
print(i)

9


In [ ]:
lst = [-10,-20,10,20,50]
new_lst = [i*2 for i in lst]
print(new_lst)

[-20, -40, 20, 40, 100]


In [ ]:
new_lst = [i**2 for i in lst ]
print(new_lst)

[100, 400, 100, 400, 2500]


In [ ]:
new_lst = [(i,i**2) for i in range(10)]
print(new_lst)

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]


In [ ]:
matrix = [          
[2,3,5],[3,4,5],[2,6,8]
]
transposed = []
for i in range(3):
  lst=[]
  for row in matrix:
    lst.append(row[i])
  transposed.append(lst)
print(transposed)    

[[2, 3, 2], [3, 4, 6], [5, 5, 8]]


In [ ]:
transposed = [[row[i] for row in matrix] for i in range(3)]
print(transposed)

[[2, 3, 2], [3, 4, 6], [5, 5, 8]]


In [ ]:
transposed = [[row[i] for row in matrix] for i in range(3)]
print(transposed)

[[2, 3, 2], [3, 4, 6], [5, 5, 8]]


Tuples


In [ ]:
t = (1,2,3)
print(t)

(1, 2, 3)


In [ ]:
tr = ("sri",1,3.4)
print(tr)

('sri', 1, 3.4)


In [ ]:
for i in tr[::2]:
  print(i)


sri
3.4


insertion sort


In [ ]:
def insertionSort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    
    j = i-1
    print(j)
    while j>=0 and arr[j] > key:    # arr = [1,10,2,20,5]
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
arr = [10000000,1000,2,20,5]
insertionSort(arr)
for val in arr:
  print(val,end=",")  

0
1
2
3
2,5,20,1000,10000000,

MergeSort

In [ ]:
def mergeSort(arr):
  if len(arr) > 1:
    mid = len(arr)//2
    left = arr[:mid]
    right = arr[mid:]
    mergeSort(left)
    mergeSort(right)
    merge(arr,left,right) 
def merge(arr,left,right):
  i=0
  j=0
  k=0
  while i < len(left) and j < len(right):
    if left[i] < right[j]:
      arr[k] = left[i]
      i+=1
    else:
      arr[k] = right[j]
      j+=1
    k+=1
    while i < len(left):
      arr[k] = left[i]
      i+=1
      k+=1
    while j < len(right):
      arr[k] = right[j]
      j+=1
      k+=1
     

arr = [54,26,93,17,77,31,44,55]
mergeSort(arr)
print(arr)

[17, 26, 54, 93, 31, 77, 44, 55]


In [ ]:
#[1,10,2,20,5]
def bubblesort(arr):
  for i in range(len(arr)):
    for j in range(len(arr)-i-1):
      print(j)
      if arr[j] > arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]
arr=[1,10,2,20,5]
bubblesort(arr)
print(arr)        

0
1
2
3
0
1
2
0
1
0
[1, 2, 5, 10, 20]


In [ ]:
def bubbleSort(arr):
  for i in range(len(arr)):
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]
arr=[1,20,10,5,6,4,9,50,23]
bubbleSort(arr)
print(arr)

[1, 4, 5, 6, 9, 10, 20, 23, 50]


QuickSort Algoritham

In [ ]:
def quicksort(arr,p,r):
  if p < r:
    q = partition(arr,p,r)
    quicksort = (arr,p,q-1)
    quicksort = (arr,q+1,r)
def partition(arr,p,r):
  pivot = arr[p]
  i = p
  for j in range(p+1,r+1):
    if arr[j] < pivot:
      i+=1
      arr[i],arr[j] = arr[j],arr[i]
  arr[p],arr[i] = arr[i],arr[p]
  return i
arr = [56,26,93,17,77,31,44,55]
quicksort(arr,0,len(arr)-1)
print(arr)       

[55, 26, 17, 31, 44, 56, 77, 93]


In [ ]:
num  = int(input())
for i in range(1,num+1):
    print("Case {}:".format(i))
    n = int(input())
    for j in range(0,n):
        l=input().split(",")
        f=int(l[0])
        if(f==0):
            print("")
            continue
        for k in range(1,f):
            print(l[k],end=", ")
        print(l[f])

KeyboardInterrupt: ignored

In [ ]:
n= int(input())
for i in range(n):
  print(i)

11
0
1
2
3
4
5
6
7
8
9
10


In [ ]:
n = int(input())
for row in range(1, n):
  for column in range(1,row+1):
    print(column,end=" ")
  print("")


6
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
n = 5
for i in range(1,n):
  for j in range(1,i+1):
    print(j,end=" ")
  print("")  

1 
1 2 
1 2 3 
1 2 3 4 


In [ ]:
num = 2
s=0
for i in range(1,11):
  s = i*2
  print(s)  

2
4
6
8
10
12
14
16
18
20


In [ ]:
list1 = [12,15,32,42,55,75,122,132,150,180,200]
for i in list1:
  if i%5 == 0 and i <= 150:
    print(i)


15
55
75
150


In [ ]:
n = int(input())
count = 0
while n != 0:
  n //=10
  count+=1
print(count)  

75869
5


In [ ]:
n = input()
count=0
for i in n:
  count += 1
print(count)

75869
5


In [ ]:
n = int(input())
m = int(input())
for row in range(0,n+1):
  for column in range(m-row,0,-1):
    print(column, end=" ")
  print()  
  

5
5
5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 



In [ ]:
list1 = [10,20,30,40,50]

for i in list1[::-1]:
  print(i)

50
40
30
20
10


In [ ]:
num = int(input())
for n in range(-10,0,1):
  print(n)

  # print(i)

10
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [ ]:
for i in range(5):
  print(i)
print("Done!")  

0
1
2
3
4
Done!


In [ ]:
def prime(start,end):
  for num in range(start,end+1):
    if num > 1:
      for i in range(2,num):
        if (num%i) ==0:
          break
      else:
        print(num)    
print(prime(25,50))      


29
31
37
41
43
47
None


In [ ]:
start = 100
end= 300
for num in range(start,end+1):
  if num > 1:
    for i in range(2,num):
      if num%i == 0:
        break
    else:
      print(num)    

101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293


In [ ]:
term = 10
num1 = 0
num2 = 1
count = 0
while count < term:
  print(num1,end= " ")
  temp = num1+num2
  num1 = num2
  num2 = temp
  count+=1
  

0 1 1 2 3 5 8 13 21 34 

In [ ]:
number = 5
factorial = 1
for i in range(1, number+1):
  factorial = factorial*i
print(factorial)  



120


TypeError: ignored

In [ ]:
for i in range(0,5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(6):
  print(i)

0
1
2
3
4
5


In [ ]:
for i in range(20,25,2):
  print(i)

20
22
24


In [ ]:
for i in range(0,15,3):
  print(i)

0
3
6
9
12


In [ ]:
for i in range(100,0,-10):
  print(i)

100
90
80
70
60
50
40
30
20
10


In [ ]:
sharks = ["hammered","great white","dogfish","frilled","bullhead","requiem"]
for shark in sharks:
  print(shark)

hammered
great white
dogfish
frilled
bullhead
requiem


In [ ]:
sharks = ['hammered','great white','dogfish','frilled','bullhead','requiem','bullhead','requiem']
for item in range(len(sharks)):
  sharks.append("shark")
print(sharks)  

['hammered', 'great white', 'dogfish', 'frilled', 'bullhead', 'requiem', 'bullhead', 'requiem', 'shark', 'shark', 'shark', 'shark', 'shark', 'shark', 'shark', 'shark']


In [ ]:
integers = []
for i in range(10):
  integers.append(i)
print(integers)  


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
n = 
s = len(n)//2
print(s)
# sr = s[]

5


In [ ]:
num_list = [1,2,3]
alpha = ['a','b','c']
for number in num_list:
  print(number)
  for letter in alpha:
    print(letter)

1
a
b
c
2
a
b
c
3
a
b
c


In [ ]:
l = [1,2,3,4,5]
l += [l.pop(0)]
print(l)

[2, 3, 4, 5, 1]


In [ ]:
arr = [1,2,3,4,5]
n= 3
for i in range(0,len(arr)):
  print(arr[i],end= " ")
for i in range(0,n):
  first = arr[0]
  for j in range(0,len(arr)-1):
    arr[j] = arr[j+1] 
  arr[len(arr)-1] = first
print()
for i in range(0,len(arr)):
  print(i)  


1 2 3 4 5 
0
1
2
3
4


In [ ]:
test_list = [1, 4, 5, 6, 7, 8, 9, 12]
  
# printing the original list
print ("The original list is : " + str(test_list))
  
# using list slicing and "+" operator
# shift last element to first
test_list = test_list[-1:] + test_list[:-1]
# printing result
print ("The list after shift is : " + str(test_list))

The original list is : [1, 4, 5, 6, 7, 8, 9, 12]
The list after shift is : [12, 1, 4, 5, 6, 7, 8, 9]


In [ ]:
def rotation (l1,l2):
  for i in l1:
    l1 = l1[1:] + l1[:1]
    if l1 == l2:
      return True
  return False
print(rotation([2,3,4,5,6],[4,5,6,2,3]))       

True


In [ ]:
Write a function that takes two lists as parameters and return the list that has the common
 elements from both the lists. The elements in the resultant list can be of arbitrary order. 
 Check your function against the sample test cases or you can add your own test cases.
Sample Input:
List1: [2, 5, 3, 4]
List2: [6, 4, 2, 4, 5]
Sample Output:
[2, 4, 5]

Sample Input:
List1: [2, 4, 1, 3, 4]
List2: [5, 3, 2, 2, 3]
Sample Output:
[2, 3] 

In [ ]:
li1 = [2,5,3,4,2]
li2 = [6,4,2,4,5]
result = []
sub = []
for i in li1:
  if i in li2:
    result.append(i)  
     
    
print(result)

[2, 5, 4, 2]


In [ ]:
def missing (arr,n):
  x1 = arr[0]
  x2 = 1
  for i in range(1,n):
    x1 ^= arr[i]
  for i in range(2,n+2):
    x2 ^= i
  return x1 ^ x2    
arr = [1,2,4,3,6,7,9,8,10]  
print(missing(arr,len(arr)))

5


In [ ]:
def algorithm(arr,n):
  rs = 0
  count=0
  for i in range(1, n):
    if arr[i] == i:
      rs = arr[i]
      count +=1
      return rs
    else:
      return rs


arr = [1,2,2,4,5,3,2,6,2,5]
print(algorithm(arr,len(arr)))           

  

0


In [ ]:
class solution:
  def createtargetarray(self,nums,index):
    nums = [0,1,2,3,4]
    index = [0,4,1,3,2]
    target = []
    length = len(nums)
    for i in range(length):
      if index[i] >= length:
        target.append(nums[i])
      else:
        target.insert(index[i],nums[i])
    return target,length
sl = solution()
print(sl.createtargetarray([0,1,2,3,4],[0,1,2,2,1]))





([0, 2, 4, 1, 3], 5)


In [ ]:
arr = [17,18,5,4,6,1]
n = len(arr)
m = arr[n-1]
arr[n-1] = -1
# print(m)
for i in range(n-2,-1,-1):
  print(i)
  temp = arr[i]
  arr[i] = m
  if temp > m:
    m = temp
print(arr)
  # print(i,end=",")

4
3
2
1
0
[18, 6, 6, 6, 1, -1]


In [ ]:
arr= [1,2,3,4,5,6,7]
target = []
n = len(arr)
for i in range(ar):
  target.append(i)
  print(target)

TypeError: ignored

In [ ]:
class Node:
  def __int__(self,info,prev = None,next=None):
    self.info = info
    self.prev = prev
    self.next = next
first = Node(10)
print(first.info)    

TypeError: ignored

In [ ]:
# product of all numbers
lst =[12,13,14,15,16,17]
product = 1
index = 0
while index < len(lst):
  product *= lst[index]
  index +=1
print("product is {}".format(product))  



product is 8910720


In [ ]:
# factorial of given number
number = 7
factorial = 0
for i in range(1,number+1):
  factorial *= i
print(factorial)  

0


In [ ]:
class Node:
  def __init__(self,info,link=None):
    self.info = info
    self.link = link
class LinkedList:    
  def insert_at_begining(self,info):
    self.head = None
    newNode = Node(info)
    if self.head != None:
      newNode.link = self.head
      self.head = newNode
    else:
      self.head = newNode
  def insert_at_end(self,info):
    newNode = Node(info)
    if self.head != None:
      current = self.head
      while current.link != None:
        current = current.link
      current.link = newNode
    else:
      self.head = newNode
  def display(self):
    current = self.head
    count = 0
    while current != None:
      count +=1
      if count > 5:
        break
      print(current.info)
LL = LinkedList()
LL.insert_at_begining(10)
LL.insert_at_begining(5)
LL.display()
print("******")
LL.insert_at_end(20)
LL.insert_at_end(30)
LL.display()                       


5
5
5
5
5
******
5
5
5
5
5


In [ ]:
#palindrome
n = input()
n = n.lower()
reverse = ""
for char in n:
  reverse = char + reverse
if reverse == n:
  print("palindrome")
else:
  print("not a palindrome")    

Madam
palindrome


In [ ]:
# palindrome
n = input()
n = n.lower()
reverse = ""
for char in n:
  reverse = char + reverse
if reverse == n:
  print("Palindrome")
else:
  print("Not Palindrome")  

Srinath
Not Palindrome


In [ ]:
n=input()
n=n.lower()
reverse=n[::-1]
if n==reverse:
  print("Palindrome")
else:
  print("Not palindrome")

Madam
Palindrome


In [ ]:
# insertion sort arr = [1,10,2,20,5]
def insertionSort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    j = i-1
    # print(j)
    while j >= 0 and key < arr[j]:
      arr[j+1] = arr[j]
      # print(arr[j+1])
      j -= 1
      print(j)
    arr[j+1] = key
arr = [1,10,2,20,5]
insertionSort(arr)
for v in arr:
  print(v,end=",")       


0
2
1
1,2,5,10,20,

In [ ]:
 for j in range(0,m):
        sline=list(map(int,input().split(" ")))
        l.append(sline)
    for p in range(1,n+1):
        a=0
        b=0
        for q in range(1,p):
            flag=0
            for e in l:
                if(p in e and q in e):
                    flag=1
            if(n1[q]==0):
                a+=flag
            else:
                b+=flag
        if(a<=b):
            n1[p]=0
           
        else:
            n1[p]=1
   

In [ ]:
# merge sort
def merge(arr,left,right):
  i = 0
  j = 0
  k = 0
  while i < len(left) and j < len(right):
    if left[i] < right[j]:
      arr[k] = left[i]
      i+=1
    else:
      arr[k] = right[j]
      j += 1
    k += 1
  while i < len(left):
    arr[k] = left[i]
    i += 1
    k += 1
  while j < len(right):
    arr[k] = right[j]
    j += 1
    k += 1          
def mergeSort(arr):
  if len(arr) > 1:
    mid = len(arr)//2
    left = arr[:mid]
    right = arr[mid:]
    mergeSort(left)
    mergeSort(right)
    merge(arr,left,right)
arr = [54,26,93,17,77,31,44,55]    
mergeSort(arr)
print(arr)

[17, 26, 31, 44, 54, 55, 77, 93]


In [ ]:
def merge(arr,left,right):
  i = 0
  j = 0
  k = 0
  while i < len(left) and j < len(right):
    if left[i] < right[j]:
      arr[k] = left[i]
      i += 1
    else:
      arr[k] = right[j]
      j+=1
    k+=1
  while i < len(left):
    arr[k] = left[i]
    i += 1
    k += 1
  while j < len(right):
    arr[k] = right[j]
    j += 1
    k += 1
def mergeSort(arr):
  if len(arr) > 1:
    mid = len(arr)//2
    left = arr[:mid]
    right = arr[mid:]
    mergeSort(left)
    mergeSort(right)
    merge(arr,left,right)
arr = [23,1,3,4,55,24,32,11,34,45]
mergeSort(arr)
print(arr)                

[1, 3, 4, 11, 23, 24, 32, 34, 45, 55]


In [ ]:
def merge(arr,left,right):
  i = 0
  j = 0
  k = 0
  while i < len(left)  and j < len(right):
    if left[i] < right[j]:
      arr[k] = left[i]
      i+=1
    else:
      arr[k] = right[j]
      j+=1
    k += 1
  while i < len(left):
    arr[k] = left[i]
    i+=1
    k+=1
  while j < len(right):
    arr[k] = right[j]
    j += 1
    k += 1
            
def mergeSort(arr):
  if len(arr) > 1:
    mid = len(arr)//2
    left = arr[:mid]
    right = arr[mid:]
    mergeSort(left)
    mergeSort(right)
    merge(arr,left,right)
arr = [2,4,56,66,89,23,43,12,44]
mergeSort(arr)
print(arr)    

[2, 4, 12, 23, 43, 44, 56, 66, 89]


In [ ]:
# bubble sort
def bubbleSort(arr):
  for i in range(len(arr)):
    for j in range(len(arr)-i-1):
      print(j)
      if arr[j] > arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]
arr = [1,10,2,20,5]
bubbleSort(arr)
print(arr)       

0
1
2
3
0
1
2
0
1
0
[1, 2, 5, 10, 20]


In [ ]:
# quickSort

def partition(arr,p,r):
  pivot = arr[p]
  i = p
  for j in range(p+1,r+1):
    if arr[j] < pivot:
       i += 1
       arr[i],arr[j] = arr[j],arr[i]
    arr[p],arr[i] = arr[i],arr[p]
    
def quickSort(arr,p,r):
  if p < r:
    q = partition(arr,p,r)
    quickSort(arr,p,q-1)
    
    quickSort(arr,q+1,r)    
arr = [54,26,93,17,77,31,44,55]
quickSort(arr,0,len(arr)-1)
print(arr)

NameError: ignored

In [ ]:
# def selectionSort
def selectionSort(arr):
  for i in range(0,len(arr)):
    min = i
    for j in range(i+1,len(arr)):
      if arr[j] < arr[min]:
        min = j
    arr[i],arr[min] = arr[min],arr[i]
arr = [10,1,2,20,5]
selectionSort(arr)
print(arr)        

[1, 2, 5, 10, 20]


In [ ]:
word = input()
message = (word + " ")*3
print(message)

srikanth
srikanth srikanth srikanth 


In [ ]:
# area of triangle
length = input()
breadth = input()
length = int(input())
breadth = int(input())
area = length*breadth
print(area)

20
30
20
30
600


In [ ]:
# first three chercters are same
first = input()
second = input()
first = first[:3]
second = second[:3]
both = first == second
print(both)

srikanth
srikanth
True


In [ ]:
a = int(input())
b = int(input())
bothPositive = a > 0 and b > 0
greater = a>5 or b > 5
result = bothPositive and greater
print(result) 

20
10
True


In [ ]:
a = input()
above = int(a)>25
b = a[0]
c = a[1]
b = int(b)
c = int(c)
great = b > c
result = above and great
print(result)



42
True


In [ ]:
char = input()
length = len(char)
last = length-1
dream = char[last]
print(dream)

srikanth
h


In [ ]:
char = input()
len_char = len(char)
half_len = int(len_char/2)
half_first = char[:half_len]
print(half_first)

srikanth
srik


In [ ]:
a = input()
b = int(input())
c = a*b
print(c)

maths
2
mathsmaths


In [ ]:
word = input()
n = int(input())
length_word = len(word)-3
slicing = word[length_word:]*n 
print(slicing)


Transport
2
ortort


In [ ]:
digits = input()
first = int(digits[0])
second = int(digits[1])
third = int(digits[2])
sum = first+second+third
print(sum)


326
11


In [ ]:
num = input()
rev = num[-1:]+num[0]
print(rev)

21
12


In [ ]:
word = input()
num = int(input())
sum = word[0:num]
su = word[num+1:]
sum = sum + su
print(sum)

combine
4
combne


In [ ]:
word = input()
length = len(word)
if length > 7:
  print("True")
else:
  print("False")  

pasword
False


In [ ]:
val = int(input())
if val > 25 and val < 75:
  print("True")
else:
  print("False")  


56
True


In [ ]:
char = input()
l = len(char)
first = char[0]
last = char[l-1]
mid = char[1:l-1]
star_len = len(mid)
mid_area = "*"*star_len
sum = first+mid_area+last
print(sum)

qwerty@2020
q*********0


In [ ]:
student_marks = int(input())
if student_marks > 50:
  print("Pass")
else:
  print("Fail")  

85
Pass


In [ ]:
first = int(input())
second = int(input())
if first > second:
  print(first)
else:
  print(second)  

4
3
4


In [ ]:
first = int(input())
second = int(input())
if first == second:
  print("Equal")
else:
  print("Not equal")  

10
5
Not equal


In [ ]:
value = int(input())
if value > 0:
  print("Positive")
elif value < 0:
  print("Negative")
else:
  print("Zero")    

0
Zero


In [ ]:
length = int(input())
breadth = int(input())
if length == breadth:
  print("Square")
else:
  print("Rectangle")  

20
20
Square


In [ ]:
salary = int(input())
bonus = int(input())
if bonus > 5:
  salary = salary*0.5
  print(salary)
else:
  print("No Bonus")  

25000
6
12500.0


In [ ]:
first = int(input())
second = int(input())
third = int(input())
sum = first+second+third
if sum == 180:
  print("It is a Triangle")
else:
  print("It is not a Triangle")  

60
60
60
It is a Triangle


In [ ]:
first = int(input())
second = int(input())
Third = int(input())
sum = first+ second
if sum > Third:
  print("It is a triangle")
else:
  print("Not a triangle") 

4
5
3
It is a triangle


In [ ]:
# lucky number
a = int(input())
b = int(input())
same = ((a ==6) or (b == 6))
both_same = (((a+b == 6) or (a-b == 6)))
if same or both_same:
  print("Lucky")
else:
  print("Not Lucky")  


2
3
Not Lucky


In [ ]:
first = int(input())
second = int(input())
third = int(input())
if first > second:
  greatest = first
else:
  greatest = second
if third > greatest:
  greatest = third
print(greatest)    


2
5
7
7


In [ ]:
# even or odd
num = int(input())
val = (num%2 == 0)
if val:
  print("Even")
else:
  print('Odd')  

3
Odd


In [ ]:
num = input()
val = num[0]
val1 = num[1]
sum = int(val)+ int(val1)
seven = val == 7 or val1 == 7
multiple = num%7 == 0
print(sum)

23
5


In [ ]:
# special eleven
number = int(input())
val = ((number % 11) == 0)
multiple = ((number % 11) == 1)
if val or multiple:
  print("Speacial number")
else:
  print("Normal number")  

23
Speacial number


In [ ]:
number = int(input())
remainder_2 = number%2
remainder_3 = number%3
if (remainder_2 == 0) and (remainder_3 == 0):
  print("Number is divisible by 6")
elif (remainder_3 == 0): 
  print("Number is divisible by 3")
elif (remainder_2 == 0):
  print("Number is divisible by 2")
else:
  print("Number is not divisible by 2,3,6")      

7
Number is not divisible by 2,3,6


In [ ]:
# power of a number
num1 = int(input())
power = int(input())
value = (num1 ** power)
print(value)


3
2
9


In [ ]:
number = input()
sd = number[0]
sd2 = number[1]
sd = int(sd)
sd2 = int(sd2)
number = int(number)
is_nine = sd == 9 or sd2 == 9
is_mul = (number % 9 == 0)

is_mul = int(is_mul)
if is_nine or is_mul:
  print("Luckiest number")
else:
  print("Unlucky number")  

29
Luckiest number


In [ ]:
 # realtion between two numbers
 

In [ ]:
first = int(input())
second = int(input())
if (first == second):
  print("A==B")
elif (first > second):
  print("A>B")
elif (first < second):
  print("A<B")    

3
4
A<B


In [ ]:
# Get grades
marks = int(input())
if marks > 85:
  print("A")
elif marks > 70 and marks <= 85:
  print("B")
elif marks >= 60 and marks <= 70:
  print("C")
elif marks < 60:
  print("F")    

63
C


In [ ]:
# Greating message
time = int(input())
if time >= 4 and time < 12:
  print("Good Morning")
elif time >= 12 and time < 16:
  print("Good afternoon")
elif time >= 16 and time < 20:  
  print("Good evening")
elif time >= 20 or time < 4:
  print('Good Night')    

7
Good Morning


In [ ]:
# Name of the polygon
name = int(input())
if name < 3:
  print("Not a polygon")
elif name == 3:
  print("Triangle")
elif name ==4:
  print("Quadrilateral")
elif name ==5:
  print("Pentagon")
else:
  print("Big Polygon")        

6
Big Polygon


In [ ]:
season = input()
if "november" or "December" or "January":
  print("Winter")
elif "Feb" or "march":
  print("Spring")  

January
Winter


In [ ]:
attendence = int(input())
medical = input()
if attendence >= 75:
  print("Allow to write the exam")
elif attendence < 75 and medical == "Y":
  print("Allowed to write the exam")
else:
  print("Cannot write the exam")  

75
Y
Allow to write the exam


In [ ]:
# Loops 
num = int(input())
for i in range(1,num+1):
  print(i)

3
1
2
3


In [ ]:
num = int(input())
count = 1
while count <= num:
  print(count)
  count+=1

3
1
2
3


In [ ]:
# print Integers - 2
number1 = int(input())
number2 = int(input())
for i in range(number1,number2+1):
  print(i)

-2
2
-2
-1
0
1
2


In [ ]:
num1 = int(input())
num2 = int(input())
while num1 <= num2:
  print(num1)
  num1 += 1

2
6
2
3
4
5
6


In [ ]:
num = int(input())
counter = 0
while counter < num:
  print("* "*num)
  counter += 1

4
* * * * 
* * * * 
* * * * 
* * * * 


In [ ]:
num = int(input())
for i in range(1,num+1):
  print("* "*num)

4
* * * * 
* * * * 
* * * * 
* * * * 


In [ ]:
row = int(input())
column = int(input())
counter = 0
while counter < row:
  print("* "*column)
  counter += 1

4
6
* * * * * * 
* * * * * * 
* * * * * * 
* * * * * * 


In [ ]:
num = int(input())
for i in range(1,num+1):
  print("* "*i)

5
* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
num = int(input())
counter = 1
while counter <= num:
  print("* "*counter)
  counter+=1

2
* 
* * 


In [ ]:
# sum of natural numbers
num = int(input())
sum = 0
for i in range(0,num+1):
  sum = sum+i
print(sum)  

6
21


In [ ]:
# sum of natural numbers
num = int(input())
count = 0
sum = 0
while count <= num:
  sum = sum + count
  count += 1
print(sum)
  


6
21


In [ ]:
# Read inputs
num = int(input())
count = 0
while count < num:
  n = int(input())
  print(n)
  count += 1

3
8
8
11
11
25
25


In [ ]:
# sum of read inputs
num  = int(input())
count = 0
sum = 0
while count < num:
  n = int(input())
  sum = sum +n
  count += 1
print(sum)  


3
10
10
10
30


In [ ]:
# print characters
word = input()
len_word = len(word)
count = 0
while count <= len_word-1:
  print(word[count])
  count+=1



srikanth
s
r
i
k
a
n
t
h


In [ ]:
num = int(input())
for i in range(1,num+1):
  print(i)

5
1
2
3
4
5


In [ ]:
m = int(input())
n = int(input())
for i in range(m,n+1):
  print(i)


2
6
2
3
4
5
6


In [ ]:
# style word
word = input()
length = len(word)
b = word[0]
for i in range(1,length):
  b = b + "-"+word[i]
print(b)  

python
p-y-t-h-o-n


In [ ]:
# Date format
date = input()
date = date.replace("-","/")
print(date)

20-20-1995
20/20/1995


In [ ]:
password = input()
contains_digit = False
for character in password:
  is_digit = character.isdigit()
  if is_digit:
    contains_digit = True
if is_digit:
  print("Valid password")
else:
  print('Invalid password')      

qwerty
Invalid password


In [ ]:
word = input()
strin = ""
for char in word:
  uppercase = char.upper()
  if uppercase == char:
    strin = strin+char.lower()
  else:
    strin = strin+char.upper()
print(strin)      

Srikanth
sRIKANTH


In [ ]:
#factorial number
num = int(input())
factorial = 1
for i in range(1,num+1):
  factorial = factorial*i
print(factorial)  

4
24


In [ ]:
m = int(input())
n = int(input())
s = 0
for i in range(m,n+1):
  s = s+i
print(s)  


2
6
20


In [ ]:
# sum of first n even numbers
m = int(input())
val = 0
for i in range(0,m+1):
  if i%2 == 0:
    val += i
print(val)    

100
2550


In [ ]:
n = int(input())
val = 0
for i in range(0,n+1):
  if i%2 == 1:
    val += i
print(val)    


6
9


In [ ]:
m  = int(input())
sum = 0
for i in range(1,m+1):
  if (i%2) == 1:
    sum = sum+i
print(sum)    



10
25


In [ ]:
# sum even numbers from m to n
m = int(input())
n = int(input())
total = 0
for i in range(m,n+1):
  if (i%2) == 0:
    total = total + i
print(total)    

2
6
12


In [ ]:
# sum odd numbers from m to n
m = int(input())
n = int(input())
total = 0
for i in range(m,n+1):
  if (i%2) == 1:
    total = total+i
print(total)    

5
13
45


In [ ]:
# sum of numbers divisible by T
T = int(input())
M = int(input())
N = int(input())
total = 0
for i in range(m,n+1):
  if i%T == 0:
    total += i
print(total)    

2
6
8
36


In [ ]:
# sum of the squares of the N natural numbers
m = int(input())
total = 0
for i in range(1,m+1):
  total = total + (i*i)
print(total)
 

3
14


In [ ]:
# sum and average of the 10 numbers
m = int(input())
sum = 0
average = 0
for i in range(1,m+1):
  sum = sum+i
  average = sum/m
 
print(average)  

5
3.0


In [ ]:
# sum of digits
num = input()
sum = 0
for i in num:
  sum = sum + int(i)
print(sum)


692
17


In [ ]:
# multiplication table
m  = int(input())
n = int(input())
for i in range(1,n+1):
  print(str(m)+" * "+str(i)+" = "+str(m*i))

2
10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [ ]:
n = input()
stri = ""
for i in n:
  stri = i +stri
print(stri)

srikanth
htnakirs


In [ ]:
# palindrome
name = input()
sr = ""
for i in name:
  sr = i + sr
if sr == name:
  print("Palindrome")
else:
  print("Not Palindrome")  

srikanth
Not Palindrome


In [ ]:
num = int(input())
great = 0
for i in range(num+1):
  n = int(input())
  if n > great:
    great = n
print("Greatest number is : ",great)

4
1
2
3
4
5
Greatest number is :  5


In [ ]:
# Smallest among N numbers
num = int(input())
smal = 0
for i in range(1,num+1):
  val = int(input())
  if smal > val:
    smal = val
print("Smallest value is : ",smal)    

3
100
200
300
Smallest value is :  0


In [ ]:
# sum of series
num = int(input())
term = "2"
total = 0
for i in range(1,num+1):
  term_1 = term*i
  total = total + int(term_1)
print(total)  

4
2468


In [ ]:
# factors of numbers
num = int(input())
val = 0
for i in range(1, num+1):
  if num%i == 0:
    print(i)   

6
1
2
3
6


In [ ]:
# Perfect number
Num = int(input())
total = 0
for i in range(1,Num+1):
  if Num%i == 0:
    total = total + i
if total == Num:
  print("Perfect number")
else:
  print("Not Perfect number")      

print(total)

21
Not Perfect number
32


In [ ]:
# Armstrong number
num = input()
length = len(num)
total = 0
for i in num:
  total = total + (int(i)**length)
if total == int(num):
  print("Armstrong number")
else:
  print("Not Armstrong number")    
  



153
Armstrong number


In [ ]:
n = int(input()) 
for i in range(n):
  if (i==0) or (i == (n-1)):
    print("* "*n)
  else:
    space = " " *(n+1)  
    print("* "+space+" *")

6
* * * * * * 
*         *
*         *
*         *
*         *
* * * * * * 


In [ ]:
num = int(input())
for i in range(num):
  if i==0 or i == (num-1):
    print("* "*num)
  else:
    space = " "*(n)
    print("* "+space+"  *")  

6
* * * * * * 
*         *
*         *
*         *
*         *
* * * * * * 


In [ ]:
# word triangle
word = input()
len_word = len(word)
for i in range(1,len(word)+1):
  print(word[:i])

Srikanth
S
Sr
Sri
Srik
Srika
Srikan
Srikant
Srikanth


In [ ]:
word = input()
len_word = len(word)
shuffle = ""
for i in range(len_word):
  index = int(input())
  shuffle = shuffle+word[index]
print(shuffle)  


srikanth
7
6
5
4
3
2
1
0
htnakirs


In [ ]:
#prime number
n = int(input())
if n > 1:
  factors = 0
else:
  factors = 1
for i in range(2,n):
  if n%i == 0:
    factors = factors + 1
if factors == 0:
  print("Prime numbers")
else:
  print("Not a prime numbers")  



-1
Not a prime numbers


In [ ]:
val = int(input())
if val > 1:
  factors = 0
else:
  factors = 1
for i in range(2,val):
  if val%i == 0:
    factors += 1
if factors == 0:
  print("prime")
else:
  print("Not prime")                  

5
prime


In [ ]:
num = int(input())
for i in range(1,num):
  if i == 0 or (i == (num-1)):
    print("* "*num)

6
* * * * * * 


In [ ]:
p = int(input())
q = int(input())

sam = 0
for i in range(1,p+1):
  if (i%2) == 0:
    if (i <= 2):
      sam += i
    if (i >= q):
      man = i   
print(sam)
print(man)


3
2
2
2


In [ ]:
# Write a function get_index(matrix) that takes a 2 dimensional list (matrix) and returns a tuple. 
#The first value in the tuple is the index of the row which has the maximum sum of all the elements in that row. 
#The second value in the tuple is the index of the column which has the maximum sum of all the elements in that column. Index starts from 0.
Sample Input and Output:
get_index([ [1,2,3], [2,1,4], [3,2,1] ]) => (1, 2) where 1 is the row index and 2 is the column index. 

In [ ]:
def get_index(matrix):
  gr = ()
  for i in range(len(matrix)):
      gr = matrix[i]

      gr = sum(gr)
      for i in range(len(gr)):
        gr = 
      
    
      print(gr)
     
      
     
print(get_index([ [1,2,3], [2,1,4], [3,2,1] ])) 

6
7
6
None


In [ ]:
get_index =  [ [1,2,3], [2,1,4], [3,2,1] ]
k = 0
for r in get_index:
  for j in r:
    k = get_index[j]
print(k)   

IndexError: ignored

In [ ]:
#  Queue
class Node:
  def __init__(self,info,next=None):
    self.info = info
    self.next = next
class Queue:
  def __init__(self):
    self.front = self.rear = None
  def isEmpty(self):
    return self.front == None
  def EnQueue(self,ele):
    temp = Node(ele)
    if self.rear == None:
      self.rear = self.front = temp
      return
    self.rear.next = temp
    self.rear = temp
  def DeQueue(self):
    if self.isEmpty():
      print("Queue empty")
      return
    else:
      temp = self.front
      self.front = temp.next
      if self.front == None:
        self.rear = None
  def display(self):
    p = self.front
    while p != None:
      print(p.info)
      p = p.next
q = Queue()
q.EnQueue(10)
q.EnQueue(20)
q.EnQueue(30)
q.display()
print("*****")
q.DeQueue()
q.DeQueue()
q.display()


10
20
30
*****
30


Arrays

In [ ]:
import array
arr = array.array('i',[2,3,4,5,6])
for arr in arr:
  print(arr)

2
3
4
5
6


In [ ]:
#unicode charecter
from array import *
arr = array('u',['a','b','c','d','e'])
for char in arr:
  print(char)

a
b
c
d
e


In [ ]:
from array import *
arr1 = array('d',[1.5,2.5,3.5,4.5])
arr2 = array(arr1.typecode,(arr*3 for arr in arr1))
for i in arr2:
  print(i)

4.5
7.5
10.5
13.5


In [ ]:
# python program to retrive the index
from array import *
x = array('i',[10,20,30,40,50])
l = len(x)
for i in range(l):
  print(x[i],end=' ')

10 20 30 40 50 

In [ ]:
#pyhton program to retrive the elements using while loop
from array import *
x = array('i',[10,20,39,40,50,60])
l = len(x)
count = 0
while count< l:
  print(x[count],end=' ')
  count+=1

10 20 39 40 50 60 

In [ ]:
# pyhton program that helps to know the effects of slicing
from array import *
x = array('i',[10,20,30,40,50,60])
y = x[1:4]
z = x[0:]
c = x[:4]
d = x[-4:]
f = x[-4:-1]
print(y)
print(z)
print(c)
print(d)
print(f)

array('i', [20, 30, 40])
array('i', [10, 20, 30, 40, 50, 60])
array('i', [10, 20, 30, 40])
array('i', [30, 40, 50, 60])
array('i', [30, 40, 50])


In [ ]:
# python program to retrie the elements using index based range
from array import *
x = array('i',[10,20,30,40,50,60,70])
for i in x[2:5]:
  print(i)

30
40
50


In [ ]:
# python program to understand various methods of arrays class
from array import *
arr = array('i',[10,20,30,40,50,60])
print("Original array",arr)
arr.append(70)
arr.append(80)
print("append array value",arr)
arr.insert(1,99)
print("insert value at index place",arr)
arr.remove(30)
print("remove value ",arr)
n = arr.pop()
print("pop value",arr)
m =arr.index(40)
print("index value",m)
lst = arr.tolist()
print("tolist",lst)

Original array array('i', [10, 20, 30, 40, 50, 60])
append array value array('i', [10, 20, 30, 40, 50, 60, 70, 80])
insert value at index place array('i', [10, 99, 20, 30, 40, 50, 60, 70, 80])
remove value  array('i', [10, 99, 20, 40, 50, 60, 70, 80])
pop value array('i', [10, 99, 20, 40, 50, 60, 70])
index value 3
tolist [10, 99, 20, 40, 50, 60, 70]


In [ ]:
# Pyhton program to storing the student marks
from array import *
str = input("enter student marks here: ").split(" ")
marks = [int(num) for num in str]
sum = 0
for i in marks:
  print(i)
  sum += i
print('total marks', sum)
n = len(marks)
percent = sum/n  
print(percent)

enter student marks here: 55 66 77 88 99
55
66
77
88
99
total marks 385
77.0


In [ ]:
# sort the array
from array import *
x = array('i',())
n = int(input())
for i in range(n):
  print("enter element: ",end=" ")
  x.append(int(input()))
print("original array",x)
# bubble sort
flag = False
for i in range(n-1):
  for j in range(n-1-i):
    if x[j] > x[j+1]:
      t = x[j] # 5  
      x[j] = x[j+1]
      x[j+1] = t
      flag = True
  if flag == False:
    break
  else:
    falg = False      
print('sorted array',x) 

5
enter element:  1
enter element:  5
enter element:  4
enter element:  3
enter element:  2
original array array('i', [1, 5, 4, 3, 2])
sorted array array('i', [1, 2, 3, 4, 5])


In [ ]:
from array import *
x = array('i',())
n = int(input())
for i in range(n):
  x.append(int(input()))
print('Original array:',x)
flag = False
for i in range(n-1):
  for j in range(n-1-i):
    if x[j] > x[j+1]:
      t = x[j]
      x[j] = x[j+1]
      x[j+1] = t
      flag =  True
  if flag == False:
    break
  else:
    flag == True
print("after sorting the array:",x)           

5
1
5
4
2
3
Original array: array('i', [1, 5, 4, 2, 3])
after sorting the array: array('i', [1, 2, 3, 4, 5])


In [ ]:
# search an element in array
from array import *
arr = array('i',())
n = int(input())
for i in range(n):
  arr.append(int(input()))
print("Original array:",arr)  
s = int(input())
flag = False
for i in range(len(arr)):
  if s == arr[i]:
    print("array is matched",i+1)
    flag = True
if flag == False:    
  print("array is not matched",)
   



5
10
20
30
20
40
Original array: array('i', [10, 20, 30, 20, 40])
20
array is matched 2
array is matched 4


Working with arrays using numpy

In [ ]:
import numpy
arr = numpy.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
from numpy import *
arr = array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
from numpy import *
arr = array(['a','b','c','d','e'])
print(arr)

['a' 'b' 'c' 'd' 'e']


In [ ]:
# python program to create using string typr array using numpy
from numpy import *
arr = array(["Hyderbad","Delhi",'Kerala',"Mumbai","Panjab",'Banglore',"Andhra","Telanagana","Madhyapradesh"])
print(arr)

['Hyderbad' 'Delhi' 'Kerala' 'Mumbai' 'Panjab' 'Banglore' 'Andhra'
 'Telanagana' 'Madhyapradesh']


In [ ]:
# Python program array 5 equal parts using linespace()
from numpy import *
arr = linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# array using upto 10 even numbers
from numpy import *
arr = arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


In [ ]:
from array import *
arr = array('i',())
n = int(input())
for i in range(n):
  arr.append(int(input()))
print("array added to the arr",arr)
flag = False
for i in range(n-1):
  for j in range(n-1-i):
    if arr[j] > arr[j+1]:
      t = arr[j]
      arr[j] = arr[j+1]
      arr[j+1] = t
      flag = True
  if flag == False:
    break
  else:
    flag = False
print("sorted array",arr)          


5
23
5
43
56
12
array added to the arr array('i', [23, 5, 43, 56, 12])
sorted array array('i', [5, 12, 23, 43, 56])


In [ ]:
# sequential search
from array import *
arr = array("i",[])
n = int(input())
for i in range(n):
  arr.append(int(input()))
print("original array",arr)
#bubble sort
flag = False
s = int(input())
print(len(arr))
for i in range(len(arr)):
  if s == arr[i]:
    print("found at position at ",i+1)
    flag = True
if flag == False:
  print("position not found5")      

5
34
35
65
2
45
original array array('i', [34, 35, 65, 2, 45])
65
5
found at position at  3


In [ ]:
import numpy
arr = numpy.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
from numpy import *
arr = array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [ ]:
from numpy import *
arr = array(['array','linkidlist','datastructure','algorithams'])
print(arr)

['array' 'linkidlist' 'datastructure' 'algorithams']


In [ ]:
from numpy import *
arr = linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
from numpy import *
a = array([10,20,30,40,50])
b = array([0,20,4,30,50])
c = a == b
print("Result of c:",c)
c = a > b
print("Result of c:",c)
c = a < b
print("Result of c:",c)

Result of c: [False  True False False  True]
Result of c: [ True False  True  True False]
Result of c: [False False False False False]


In [ ]:
from numpy import *
a = array([10,20,30,40,50],int)
b = array([1,21,3,40,50],int)
d = where(a>b,a,b)
print(d)

[10 21 30 40 50]


In [ ]:
from numpy import *
a = array([1,2,0,-1,0,6],int)
c = nonzero(a)
for i in c:
  print(i)
print(a[c])  

[0 1 3 5]
[ 1  2 -1  6]


In [ ]:
from numpy import *
a = array([10,20,30,40,50])
b = array([20,50,30,35,55])
c = where(a > b, a, b)
print(c)

[20 50 30 40 55]


In [ ]:
# slicing
from numpy import *
a = arange(1,16)
print(a)
b = a[1:16:2]
print(b)
c = b[::]
print(c)
e = b[-2:2:-1]
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14]
[ 2  4  6  8 10 12 14]
[12 10  8]


In [ ]:
# slicing operation using numpy and while loop also using here
from numpy import *
a = arange(10,16)
print(a)
a = a[1::2]
print(a)
count = 0
while count < len(a):
  print(a[count])
  count+=1

[10 11 12 13 14 15]
[11 13 15]
11
13
15


In [ ]:
# 2Darray
from numpy import *
arr = array([[1,2,3],[3,4,5]])
print(arr.ndim)

2


In [ ]:
# reshape 
from numpy import *
arr = arange(10)
print(arr)
arr1 = arr.reshape(2,5)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
from numpy import *
a = [[1,2,3],[2,3,4],[7,8,9]]
for i in range(len(a)):
  print(a[i])
for i in range(len(a)):
  for j in range(len(a)):
   
    print(a[i][j],end=" ") 
     

[1, 2, 3]
[2, 3, 4]
[7, 8, 9]
1 2 3 2 3 4 7 8 9 

In [ ]:
from numpy import *
a = [[[1,2,3],
     [4,5,6]],
     [[7,8,9],
      [0,11,12]]]
for i in range(len(a)):
  for j in range(len(a[i])):
    for k in range(len(a[i][j])):
      print(a[i][j][k],end =" ")
    print()
  print()           

1 2 3 
4 5 6 

7 8 9 
0 11 12 



In [ ]:
# selection sort
def selectionSort(arr):
  for i in range(0,len(arr)):
    min_index = i
    for j in range(i+1,len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    arr[i],arr[min_index] = arr[min_index],arr[i]
arr = [10,1,5,3,6,2]
selectionSort(arr)
for v in arr:
  print(v)       

1
2
3
5
6
10


In [ ]:
def SelectionSort(arr):
  for i in range(0,len(arr)):
    min_index = i
    for j in range(i+1,len(arr)):
      if arr[j] < arr[min_index]:
        min_index = j
    arr[i],arr[min_index] = arr[min_index],arr[i]
arr = [5,2,1,6,3,7]
selectionSort(arr)
for v in arr:
  print(v)      

1
2
3
5
6
7


In [ ]:
# quickSort
def quickSort(arr,p,r):
  if p < r:
    q = partition(arr,p,r)
    quickSort(arr,p,q-1)
    quickSort(arr,q+1,r)
def partition (arr,p,r):
  pivot = arr[p]
  i = p
  for j in range(p+1,r+1):
    if arr[j] < pivot:
      i+=1
      arr[i],arr[j] =arr[j], arr[i]
  arr[p],arr[i] = arr[i],arr[p]
  return i
arr = [54,26,93,17,77,31,44,55]
quickSort(arr,0,len(arr)-1)
print(arr)              

[17, 26, 31, 44, 54, 55, 77, 93]


In [ ]:
# bubble sort
def bubbleSort(arr):
  for i in range(len(arr)):
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]
arr = [1,10,2,20,5]
bubbleSort(arr)
print(arr)        

[1, 2, 5, 10, 20]


In [ ]:
# insertionSort
def insertionSort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    j = i-1
    # print(key)
    while j>=0 and key < arr[j]:
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
arr = [1,10,2,20,5]
insertionSort(arr)
print(arr)      

[1, 2, 5, 10, 20]


In [ ]:
# insertion sort arr = [1,10,2,20,5]

def insertionSort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    j = i-1
    while j >= 0 and key < arr[j]:
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
arr = [1,10,2,20,5] 
insertionSort(arr)
print(arr)     

[1, 2, 5, 10, 20]


In [ ]:
# arr = [1,10,2,20,5]
def insertionSort(arr):
  for i in range(1,len(arr)):
    key = arr[i]
    j = i-1
    while j >= 0 and key < arr[j]:
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
arr = [1,10,2,5,20]
insertionSort(arr)
print(arr)      

[1, 2, 5, 10, 20]


In [ ]:
# MergeSort arr = [6,5,3,1,8,7,2,4]

def mergeSort(arr,left,right):
  if left < right:
    mergeSort(arr,)


In [ ]:
#lists
player = ['player',183,148,123.64,False]
print(player)

['player', 183, 148, 123.64, False]


In [ ]:
#list concatintion
number = [120,30,40,50,60,45]
lid = int(input())
val = [lid]+number
val1 = number+[lid]
print(val)
print(val1)


23
[23, 120, 30, 40, 50, 60, 45]
[120, 30, 40, 50, 60, 45, 23]


In [ ]:
# convert string to list
digit = input("enter the digit ")
val = list(digit)
print(val)

enter the digit Python
['P', 'y', 't', 'h', 'o', 'n']


In [ ]:
# List of indexing
color_list = ['Red','Orange','Yellow','Pink','Green','Blue','Purple','Black','White']
index = int(input("enter the value here:"))
print(color_list[index])

enter the value here:4
Green


In [ ]:
# List indexing
Programing_languages = ["Python","Java","Ruby","DBMS","C","C++","Go","R","Javascript"]
n = int(input())
for i in range(n):
  index = int(input())
  print(Programing_languages[index])

4
3
DBMS
2
Ruby
1
Java
5
C++


In [ ]:
# List Repetition
m = int(input())
n = int(input())
val = [m]*n
print(val)

23
2
[23, 23]


In [ ]:
# Greater than N
num_list = [1,6,32,93,71,-20,30,-90,50]
new = []
num = int(input())
for i in num_list:
  if i > num:
    new = new +[i]
print(new)    
    

50
[93, 71]


In [ ]:
n = int(input())
new = []
for i in range(n):
  val = input()
  new += [val]
print(new)  


5
Tiger
cinema
5.5
93
20
['Tiger', 'cinema', '5.5', '93', '20']


In [ ]:
# Reverse order
n = int(input())
new = []
for num in range(n):
  val = input()
  new = [val] + new
for i in new:  
  print(i)  

5
Anjali
Ravi
Akbar
Suresh
Gopal
Gopal
Suresh
Akbar
Ravi
Anjali


In [ ]:
#List concatination
n = int(input())
new = []
for i in range(n):
  val = input()
  new += [val]
new_val = new[0:3]+new[-3:]
print(new_val)  


8
Anjali
Ravi
Akbar
Suresh
Gopal
Latha
Mohan
Ashok
['Anjali', 'Ravi', 'Akbar', 'Latha', 'Mohan', 'Ashok']


In [ ]:
# functions
dig = "Banana Apple Pomegranate Strawberry Grapes Orange"
new = ""
val = dig.split()
for word in val:
  print(word)

Banana
Apple
Pomegranate
Strawberry
Grapes
Orange


In [ ]:
n = "Banana Apple Pomegranate Strawberry Grapes Orange"
word_list = n.split()
for word in word_list:
  print(word)

Banana
Apple
Pomegranate
Strawberry
Grapes
Orange


In [ ]:
val = "Banana Apple Pomegranate Strawberry Grapes Orange"
dig = val.split()
new = dig[::-1]
print(new)

['Orange', 'Grapes', 'Strawberry', 'Pomegranate', 'Apple', 'Banana']


In [ ]:
n = "2 5 10 -15 3"
num_list = n.split()
total = 0
for word in num_list:
  total += int(word)

print(total)

5


In [ ]:
# reverse the letters in words of the sentence
# word = '''The output should be a single line containing the sentence by reversing all the letters in words.
#  Note: The order of the words in the modified sentence should be the same as in the given sentence.
# Explanation'''
# new = word.split()
# modified = []
# for i in new:
#   modified += [i[::-1]]
# reverse_order = " ".join(modified)  
# print(reverse_order)



['The', 'output', 'should', 'be', 'a', 'single', 'line', 'containing', 'the', 'sentence', 'by', 'reversing', 'all', 'the', 'letters', 'in', 'words.', 'Note:', 'The', 'order', 'of', 'the', 'words', 'in', 'the', 'modified', 'sentence', 'should', 'be', 'the', 'same', 'as', 'in', 'the', 'given', 'sentence.', 'Explanation']


In [ ]:
list_a = "1,2,3"
list_b = "4,5,6"
n = len(list_a)
for 

In [ ]:
list_a = input().split(",")
list_b = input().split(",")
len_a = len(list_a)
n = len_a-1
for i in range(len_a):
  print("**",i)
  num_1 = list_a[i]
  num_2 = list_b[n-i]
  result = str(num_1)+ " "+str(num_2)
  print(result)

1,2,3
4,5,6
** 0
1 6
** 1
2 5
** 2
3 4


In [ ]:
# functions coding practice
# Return the given argument
def func(arg_1):
  return arg_1
n = "Srikanth"
func(n)
print(n)  

Srikanth


In [ ]:
def func(n):
  for i in range(1,11):
    print(str(n)+"*"+str(i)+"="+str(n*i))
n = int(input())
func(n)
 



5
5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


In [ ]:
# Welcome message
def message(a):
  wishes = "Welcome"+" "+a
  print(wishes)
a = input()
message(a)


Srikanth
Welcome Srikanth


In [ ]:
# Multiply with other number
def multiply(m,n):
  m = m*n
  print(m)
m = int(input())
n = int(input())
multiply(m,n)  

2
100
200


In [ ]:
# Divisible by 7
def divi(a,b):
  remainder = a%b
  if remainder == 0:
    result = True
  else:
    result = False
  print(result)
a=int(input())
b=int(input())
divi(a,b)      

14
7
True


In [ ]:
#Perimeter of the square
def perimeter(arg_1):
  return arg_1*4
arg_1 = int(input())
result = perimeter(side)
print(result)  

3
12


In [ ]:
#add two numbers
def add(m,n):
  sum = m+n
  return sum
m = int(input())
n = int(input())
add(m,n)


5
8


13

In [ ]:
# printing message
def message(m,n):
  msg = m+" is "+str(n)+" years old "
  print(msg)
m = input() 
n = int(input())
message(m,n) 

Srikanth
26
Srikanth is 26 years old 


In [ ]:
def get(arg):
  
  list_a = arg.split(",")
  len_a = len(list_a)
  for i in range(len_a):
    list_a[i] = int(list_a[i])**2
  return list_a
arg = input()
number = get(arg)
print(number)    

1,2,3,4


IndexError: ignored

In [ ]:
# Team points
def calculate_league_points(wins, draws, losses):

    win_points = wins*4
    draw_points = draws*2
    loss_points = losses*-1
    total_points = win_points + loss_points + draw_points
    return total_points


statistics = input().split(",")
wins = int(statistics[0])
draws = int(statistics[1])
losses = int(statistics[2])
total_points = calculate_league_points(wins, draws, losses)
print(total_points) 

4,1,2
16


In [ ]:
# speed meter
def speedo(speed):
  if speed < 60:
    res = "Normal"
  elif (speed >= 60) and (speed < 80):
    res = "Warning"
  else:
    res = "Overspeed"
  return res
speed = int(input())
speedo(speed)
        

50


'Normal'

In [ ]:
# sum of squares
def sum_of_squares(m,n):
  total = 0
  for i in range(m,n+1):
    total = total + (i**2)
  return total
m = int(input())
n = int(input()) 
result = sum_of_squares(m,n)
print(result)   

3
5
50


In [ ]:
# sum_of cubes
def sum_of_cubes(m,n):
  total = 0
  for i in range(m,n+1):
    total = total+(i**3)
  return total
m = int(input())
n = int(input())
result = sum_of_cubes(m,n)
print(result)    

3
5
216


In [ ]:
# Labelling numbers
def show_numbers(number):
  for i in range(number):
    if i%2 == 0:
      print(str(i)+" Even")
    else:
      print(str(i)+" Odd")  
  
number = int(input())    
show_numbers(number)    

6
0 Even
1 Odd
2 Even
3 Odd
4 Even
5 Odd


In [ ]:
# U


PreMium


In [ ]:
#count the vowels
def count_the_vowels(word):
  count = 0
  for letter in word:
    is_a = letter == "a"
    is_e = letter == "e"
    is_i = letter == "i"
    is_o = letter == "o"
    is_u = letter == "u"
    is_vowel = ((((is_a or is_e) or is_i) or is_o) or is_u)
    if is_vowel:
      count += 1
  return count    
dg = input()
count_the_vowels(dg)      

suggestions


4

In [ ]:
#four passengers and driver
def number_of_cars_needed(no_of_people):
  number_of_cars = no_of_people//5
  remaining_people = no_of_people%5
  if remaining_people > 0:
    number_of_cars += 1
  return number_of_cars
no_of_people = int(input())
number_of_cars_needed(no_of_people)  



5


1

In [ ]:
def valid_pin(num):
  if len(num) == 4 or len(num) == 6:
    if num.isdigit():
      print("valid pin code")
    else:
      print("invalid pin code")
num = input()
valid_pin(num)              

156157
valid pin code


In [ ]:
#largest number
number = "2,3,-1,50"
val = number.split(",")
len_list = len(val)
for word in range(len_list):
  val[word] = int(val[word])
sor = sorted(val)
largest = sor[-1]
print(largest)  
  


50


In [ ]:
# smallest number
number = "2,3,-1,50"
val = number.split(",")
len_val = len(val)
for word in range(len_val):
  val[word] = int(val[word])
val = sorted(val)
smallest = val[0]
print(smallest)  

-1


In [ ]:
#kth largest number
number = "2,3,-1,5"
k = int(input())
word = number.split(",")
len_number = len(word)
for i in range(len_number):
  word[i] = int(word[i])
val = sorted(word)
largest = val[-k]
print(largest)

2
3


In [ ]:
# Kth smallest number
number = "2,3,-1,5"
k = int(input())
n = number.split(",")
len_number = len(n)
for i in range(len_number):
  n[i] = int(n[i])
sor = sorted(n)
smallest = sor[k-1]
print(smallest)  

2
2


In [ ]:
# difference between Max and Min
number = "2,3,-1,5"
num_list = number.split(",")
len_list = len(num_list)
for i in range(len_list):
  num_list[i] = int(num_list[i])
sort_list = sorted(num_list)
max_num = max(sort_list) 
min_num = min(sort_list)
difference = max_num - min_num
print(difference) 

6


In [ ]:
# Extract Digits
def get_digit(word):
  list_val = []
# word = "COd1n8"
  for i in word:
    if i.isdigit():
      list_val += [int(i)]
  return list_val  



word = input()
lev = get_digit(word)
sum_of_digits = sum(lev)
print(sum_of_digits)
max_val = max(lev)
print(max_val)
min_val = min(lev)
print(min_val)

C0d1n8
9
8
0


In [ ]:
# sort and square the list 
# list_a = input().split()
# list_x = []

# for num in list_a:
#   list_x += int(num)**2
# print(list_x)

In [ ]:
#Factorial 
def fact(n):
  if n <= 0:
    return 1
  else:
    return n*fact(n-1)
n = int(input())
fact(n)            

4


24

In [ ]:
#Sum of digits
def sum_of_digit(val):
  if val < 10:
    return val
  else:
    return (val % 10)+ sum_of_digit(val//10)
val = int(input())
d = sum_of_digit(val)
print(d)     

255
12


In [ ]:
a = 255
b = a%10
print(b)

5


In [ ]:
a=2555//10
print(a)


255


In [ ]:
# a power of b
def cal(x,y):
  if y == 1:
    return x
  else:
    y -= 1
    return x*cal(x,y)
x = int(input())
y = int(input())
d = cal(x,y)
print(d)      

2
3
8


In [ ]:
# sum of numbers
def sum_num(n):
  if n == 1:
    return 1
  else:
    return n+sum_num(n-1)
n = int(input())
val = sum_num(n)          
print(val)

4
10


In [ ]:
def sum_val(n):
  if n == 1:
    return 1
  else:
    return n * sum_val(n-1)
n = int(input())
d = sum_val(n)
print(d)      

4
24


In [ ]:
# List append 
word = ['cricket','hockey','football','badminton']
val = input()
word.append(val)
print(word)

Golf
['cricket', 'hockey', 'football', 'badminton', 'Golf']


In [ ]:
# insert an element
word = [10,20,40,50,60]
val = int(input())
index = int(input())
word.insert(index,val)
print(word)

30
2
[10, 20, 30, 40, 50, 60]


In [ ]:
# remove the last 3 elements
programing_languages = ['Python','C','Java','Ruby','C++','CSS','HTML','Bash','Perl','R','Swift','SQL','Php','Javascript']
n = int(input())
for i in range(n):
  programing_languages.pop()
print(programing_languages)  

3
['Python', 'C', 'Java', 'Ruby', 'C++', 'CSS', 'HTML', 'Bash', 'Perl', 'R', 'Swift']


In [ ]:
# count the occurrences
num_list = [5, 10, 20, 35, 5, 50, 20, 100, 200, 10, 150, 100, 100, 20, 20]
val = int(input())
occurrences = num_list.count(val)
print(occurrences)

100
3


In [ ]:
# Remove all the occurrences
num_list = [5, 10, 20, 35, 5, 50, 20, 100, 200, 10, 150, 100, 100]
val = int(input())
res = num_list.count(val)
for i in range(res):
  num_list.remove(val)
print(num_list)

5
[10, 20, 35, 50, 20, 100, 200, 10, 150, 100, 100]


In [ ]:
# Nth term fibonacci series
def fibonacci(n):
  if n <= 1:
    return n
  else:
    return fibonacci(n-1)+fibonacci(n-2)
n = int(input())
result = fibonacci(n)      
print(result)

5
5


In [ ]:
def febo(der):
  if der <= 1:
    return 1
  else:
    return der*febo(der-1)
der = int(input())
febo(der)      

5


120

In [ ]:
def fibonacci(n):
    if n<=1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)
n=int(input())
result=fibonacci(n)
print(result)

5
5


In [ ]:
def fibonacci(n):
  if n <= 1:
    return n
  else:
    return fibonacci(n-1)+fibonacci(n-2)

def get_fibonacci_series(n):
  fibonacci_series = []
  for i in range(n):
    term = fibonacci(i)
    print(term)
    fibonacci_series.append(term)
  return fibonacci_series
n = int(input())
result = get_fibonacci_series(n)
print(result)          

5
0
1
1
2
3
[0, 1, 1, 2, 3]


In [ ]:
n = int(input())
srm = []
for i in range(n):
  val = input()
  srm.append(val)
print(srm)  


5
10
20
30
40
50
['10', '20', '30', '40', '50']


In [ ]:
num_list = [(10, 20, 30), (1, 2), (5, 10, 15, 45)]
n = int(input())
new_list = []
for tup in new_list:
  update_val = tup[:-1]+(n,)
  new_list.append(update_val)
print(new_list)


# num_list = [(10, 20, 30), (1, 2), (5, 10, 15, 45)]
# n=int(input())
# new_list = []
# for tuple_a in num_list:
#     update_tuple = tuple_a[:-1]+(n,)
#     new_list.append(update_tuple)
# print(new_list)

[(10, 20, 50), (1, 50), (5, 10, 15, 50)]


In [ ]:
def common(num_list):
    new_list = []
    for item in num_list:
      num = int(item)
      new_list.append(num)
    return new_list  
  
  
num_list =  "5,10,15,20,10,30,15"
list_a = num_list.split(",")
list_a = common(list_a)
set_a = set(list_a)
list_a = list(set_a)
print(list_a)






[5, 10, 15, 20, 30]


In [ ]:
num_list =  "5,10,15,20,10,30,15"
val_list = num_list.split(",")
val = []
for num in val_list:
  stor = int(num)
  val.append(stor)
print(set(val))  
# print(type(val_list))

{5, 10, 15, 20, 30}


In [ ]:
# remove multiple duplicates
num_set = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100}
list_a  = input().split(",")
for item in list_a:
    num = int(item)
    num_set.discard(num)
num_list = list(num_set)
num_list.sort()
print(num_list)


20,40,80
[10, 30, 50, 60, 70, 90, 100]


In [ ]:
multiplies_of_2 = {2, 4, 6, 8, 10}
multiplies_of_3 = {3, 6, 9, 12, 15}
val = []
for i in multiplies_of_2:
  if i not in multiplies_of_3:
    val.append(i)
for j in multiplies_of_3:
  if j not in multiplies_of_2:
    val.append(j)    
   
digi = val
digi.sort(reverse = False)

print(digi) 


[2, 3, 4, 8, 9, 10, 12, 15]


In [ ]:
# convert list into tuple
str_a = input()
a = str_a.split(",")
i = 0
for item in a:
  a[i] = int(item)
  i += 1
a = tuple(a)
print(a)  

 


5,10,15,20,25,30
(5, 10, 15, 20, 25, 30)


In [ ]:
# Common elements
# def commonElements(val):

str_1 = "1,2,3,4,5,6"
str_2 = "2,4,5,9,10" 
ans_a = []
ans_b = []
lf = []
str_a = str_1.split(",")
str_b = str_2.split(",")
for num_1 in str_a:
  val = int(num_1)
  ans_a.append(val)
  # print(val)
for num_2 in str_b: 
  mal = int(num_2)
  ans_b.append(mal)
for i in ans_a:
  if i in ans_b:
    lf.append(i)
print(lf)
  
# print(ans_a)
# print(ans_b)

 
    

[2, 4, 5]


In [ ]:
n = int(input())
multiply_2 = set()
multiply_3 = set()
val = []
mal = []
for i in range(1, n+1):
  multiply_2.add(i*2)
  multiply_3.add(i*3)
for j in multiply_2:
  if j not in multiply_3:
    val.append(j)
for m in multiply_3:
  if m not in multiply_2:
    mal.append(m)
val = val+mal   
val.sort() 
print(val)    
# print(mal)   


5
[2, 3, 4, 8, 9, 10, 12, 15]


In [ ]:
# Add item to set
set_a = {"Pencil"}
word = input()
set_a.update([word])
list_a = sort(set_a)


['Pen', 'Pencil']
